require_relative("../core/lamp.rb")

class Docs

	include Lamp

	def initialize 

		@name = "Documentation"
		@alia = "DOCS"
		@docs = "Automatic documentation toolkit"

	end

	def isListening

		return true

	end

	def application input

		respond("TODO")
		generate("README.md",docs_README)

	end

	def docs_README

		text = ""
		data = $jiin.command("disk load system")["DOCS"]
		text += "# Jiin #{data["VERS"]}\n"
		text += data["MAIN"]+"\n"

		text += "\nGenerated by DOCS"


		return text

	end

	def commit

	end

	def generate path, content

		out_file = File.new(path, "w")
		out_file.puts(content)
		out_file.close

		puts "@ Created #{path}"
	end

end